name: CI/CD Pipeline with Input Validation Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  input-validation-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install Dependencies
      run: composer install 

    - name: Run Unit Tests
      run: ./vendor/bin/phpunit --filter 'InputValidation'

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Node.js Dependencies
      run: npm install

    - name: Run E2E Tests
      run: npm run e2e
